// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehvqhenukzeaciynbmwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVodnFoZW51a3plYWNpeW5ibXdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODY5MjMsImV4cCI6MjA1NzI2MjkyM30.YgEn11LzxpFyjGlW06Zr6Ua3Pm7P6_Y36dqVMHc1cIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);